[package]
name = "leightbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
signal-hook = "0.3.15"
termion = "2.0.1"

